# Generated by Django 6.0.4 on 2026-04-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('producent', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('numer_inwentarzowy', models.CharField(max_length=30, unique=True)),
                ('data_zakupu', models.DateField()),
                ('sprawny', models.BooleanField(default=True)),
            ],
        ),
    ]
