# Generated by Django 6.0.4 on 2026-04-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strazak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('stopien', models.CharField(choices=[('strazak', 'Strażak'), ('kierowca', 'Kierowca'), ('dowodca', 'Dowódca'), ('naczelnik', 'Naczelnik')], default='strazak', max_length=30)),
                ('data_badan', models.DateField(verbose_name='Data ważności badań')),
            ],
            options={
                'verbose_name': 'Strażak',
                'verbose_name_plural': 'Strażacy',
            },
        ),
        migrations.AlterModelOptions(
            name='sprzet',
            options={'verbose_name': 'Sprzęt', 'verbose_name_plural': 'Sprzęt'},
        ),
    ]
