# Generated by Django 6.0.4 on 2026-04-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0002_strazak_alter_sprzet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strazak',
            name='stopien',
            field=models.CharField(choices=[('strazak', 'Strażak'), ('strazak-ratownik', 'Strażak-ratownik'), ('kierowca', 'Kierowca'), ('dowodca', 'Dowódca'), ('naczelnik', 'Naczelnik')], default='strazak', max_length=30),
        ),
    ]
