# Generated by Django 6.0.4 on 2026-04-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0003_alter_strazak_stopien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_zdarzenia', models.CharField(max_length=20, unique=True)),
                ('rodzaj', models.CharField(choices=[('pozar', 'Pożar'), ('wypadek', 'Wypadek'), ('miejscowe', 'Miejscowe Zagrożenie'), ('falszywy', 'Alarm Fałszywy'), ('zabezpieczenie', 'Zabezpieczenie Eventu'), ('gospodarczy', 'Wyjazd Gospodarczy')], max_length=20)),
                ('miejsce', models.CharField(max_length=200)),
                ('data_godzina_wyjazdu', models.DateTimeField()),
                ('opis', models.TextField(blank=True)),
                ('dowodca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prowadzone_akcje', to='remiza.strazak')),
                ('pojazd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='remiza.sprzet')),
            ],
            options={
                'verbose_name': 'Akcja Ratownicza',
                'verbose_name_plural': 'Akcje Ratownicze',
            },
        ),
    ]
