# Generated by Django 6.0.4 on 2026-04-24 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0004_akcja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pojazd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('oznaczenie', models.CharField(max_length=20)),
                ('numer_operacyjny', models.CharField(max_length=20, unique=True)),
                ('sprawny', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pojazd i Łódź',
                'verbose_name_plural': 'Pojazdy i Łodzie',
            },
        ),
        migrations.AlterField(
            model_name='akcja',
            name='pojazd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='remiza.pojazd', verbose_name='Pojazd'),
        ),
    ]
