# Generated by Django 6.0.4 on 2026-04-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0005_pojazd_alter_akcja_pojazd'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcja',
            name='ratownicy',
            field=models.ManyToManyField(related_name='udzial_w_akcjach', to='remiza.strazak', verbose_name='Skład osobowy'),
        ),
    ]
