# Generated by Django 6.0.4 on 2026-04-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0006_akcja_ratownicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcja',
            name='data_godzina_powrotu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
