# Generated by Django 5.2.14 on 2026-05-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0007_akcja_data_godzina_powrotu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='data_oc',
            field=models.DateField(blank=True, null=True, verbose_name='Data ubezpieczenia OC'),
        ),
        migrations.AddField(
            model_name='pojazd',
            name='data_przegladu',
            field=models.DateField(blank=True, null=True, verbose_name='Data przeglądu'),
        ),
        migrations.AlterField(
            model_name='akcja',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='strazak',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
