# Generated by Django 6.0.5 on 2026-05-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0008_pojazd_data_oc_pojazd_data_przegladu_alter_akcja_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akcja',
            name='pojazd',
        ),
        migrations.AddField(
            model_name='akcja',
            name='pojazdy',
            field=models.ManyToManyField(related_name='akcje', to='remiza.pojazd', verbose_name='Pojazdy biorące udział'),
        ),
        migrations.AlterField(
            model_name='akcja',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='strazak',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
