# Generated by Django 5.2.14 on 2026-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0010_alter_akcja_id_alter_pojazd_id_alter_sprzet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='notatki',
            field=models.TextField(blank=True, verbose_name='Notatki / Serwis'),
        ),
    ]
