# Generated by Django 5.2.14 on 2026-05-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0013_alter_akcja_id_alter_pojazd_id_alter_sprzet_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wydarzenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Nazwa wydarzenia')),
                ('data', models.DateField(verbose_name='Data wydarzenia')),
                ('notatki', models.TextField(blank=True, verbose_name='Notatki')),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
            },
        ),
    ]
