# Generated by Django 5.2.14 on 2026-05-26 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0014_wydarzenie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strazak',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_strazaka', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strazak',
            name='imie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='strazak',
            name='nazwisko',
            field=models.CharField(max_length=100),
        ),
    ]
