# Generated by Django 6.0.5 on 2026-05-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0015_strazak_user_alter_strazak_imie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strazak',
            name='kurs_dowodca',
            field=models.BooleanField(default=False, verbose_name='Kurs dowódców'),
        ),
        migrations.AddField(
            model_name='strazak',
            name='kurs_podstawowy',
            field=models.BooleanField(default=False, verbose_name='Kurs podstawowy OSP'),
        ),
        migrations.AddField(
            model_name='strazak',
            name='waznosc_kpp',
            field=models.DateField(blank=True, null=True, verbose_name='Data ważności KPP'),
        ),
        migrations.AlterField(
            model_name='akcja',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='strazak',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
