# Generated by Django 5.2.14 on 2026-05-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0016_strazak_kurs_dowodca_strazak_kurs_podstawowy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='przebieg',
            field=models.PositiveIntegerField(default=0, verbose_name='Aktualny przebieg (km)'),
        ),
        migrations.AddField(
            model_name='sprzet',
            name='motogodziny',
            field=models.FloatField(default=0.0, verbose_name='Aktualny stan motogodzin (MTH)'),
        ),
        migrations.AlterField(
            model_name='akcja',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='strazak',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
