# Generated by Django 5.2.14 on 2026-05-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0017_pojazd_przebieg_sprzet_motogodziny_alter_akcja_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcja',
            name='liczniki_pojazdow_po',
            field=models.JSONField(blank=True, default=dict, verbose_name='Stany liczników pojazdów po akcji'),
        ),
        migrations.AddField(
            model_name='akcja',
            name='motogodziny_sprzetu_po',
            field=models.JSONField(blank=True, default=dict, verbose_name='Stany motogodzin sprzętu po akcji'),
        ),
    ]
