# Generated by Django 5.2.14 on 2026-05-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiza', '0018_akcja_liczniki_pojazdow_po_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='czy_silnikowy',
            field=models.BooleanField(default=False, verbose_name='Czy sprzęt posiada silnik?'),
        ),
    ]
